version: 1.0.{build}
build_script:
- cmd: >-
    mkdir installdir

    mkdir builddir

    cd builddir

    cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX:PATH=C:/projects/libonvif/installdir -DCMAKE_PREFIX_PATH:PATH="C:/OpenSSL-Win64" -DQt5_DIR:PATH="C:/Qt/5.10.1/msvc2015_64/lib/cmake/Qt5" C:/projects/libonvif

    cmake --build .
test: off
deploy: off