language: cpp
compiler: gcc
dist: trusty
sudo: required
os: linux
before_script:
- sudo apt-get update
- sudo apt-get install qt5-default
script:
- echo $PWD
- mkdir builddir && mkdir installdir
- cd builddir
- cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/projects/libonvif/installdir ../