language: cpp
compiler: gcc
dist: trusty
sudo: required
os: linux
before_script:
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-default
script:
- mkdir builddir && mkdir installdir
- cd builddir
- cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/home/travis/build/Tereius/libONVIF/installdir ../
- make